[versions]
# Core Versions
minecraft = "1.20.6"
java = "17"
neoform = "1.20.6-20240627.102356"

# Parchment
parchment-minecraft = "1.20.6"
parchment = "2024.06.16"

# Fabric
fabric-loader = "0.18.4"
fabric-api = "0.100.8+1.20.6"
modmenu = "10.0.0"

# NeoForge
neoforge = "20.6.139"

# Forge
forge = "50.2.0"

# Libraries
mixin = "0.8.5"
mixinextras = "0.4.1"
gson = "2.10.1"
forge-config-api-port = "20.6.1"

# Gradle Plugins
fabric-loom-plugin = "1.15-SNAPSHOT"
neoforge-moddev-plugin = "2.0.140"
modpublisher-plugin = "2.1.6"
forgegradle-plugin = "[6.0.47,6.2)"
mixin-plugin = "0.7-SNAPSHOT"

[libraries]
# Core Dependencies
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Mixin
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixin-extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

# Forge
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

# Parchment
parchment = { group = "org.parchmentmc.data", name = "parchment-1.20.6", version.ref = "parchment" }



# Forge Config API Port (template-style aliases)
forge-config-api-port-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "forge-config-api-port" }
forge-config-api-port-neoforge = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-neoforge", version.ref = "forge-config-api-port" }
forge-config-api-port-common-neoforgeapi = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forge-config-api-port" }
forge-config-api-port-forge = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-forge", version.ref = "forge-config-api-port" }
[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom-plugin" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev-plugin" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher-plugin" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle-plugin" }
mixin = { id = "org.spongepowered.mixin", version.ref = "mixin-plugin" }
