[versions]
# Core Versions
minecraft = "1.20.3"
java = "17"
neoform = "1.20.3-20241215.201103"

# Parchment
parchment-minecraft = "1.20.3"
parchment = "2023.12.31"

# Fabric
fabric-loader = "0.18.4"
fabric-api = "0.91.1+1.20.3"
modmenu = "9.0.0"

# NeoForge
neoforge = "20.3.8-beta"

# Forge
forge = "49.0.2"

# Libraries
forge-config-api-port = "20.2.6"
mixin = "0.8.5"
mixinextras = "0.4.1"
gson = "2.10.1"

# Gradle Plugins
fabric-loom-plugin = "1.15-SNAPSHOT"
neoforge-moddev-plugin = "2.0.140"
modpublisher-plugin = "2.1.6"
forgegradle-plugin = "[6.0.47,6.2)"
mixin-plugin = "0.7-SNAPSHOT"

[libraries]
# Core Dependencies
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Mixin
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixin-extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

# Forge
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

# Parchment
parchment = { group = "org.parchmentmc.data", name = "parchment-1.20.3", version.ref = "parchment" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom-plugin" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev-plugin" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher-plugin" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle-plugin" }
mixin = { id = "org.spongepowered.mixin", version.ref = "mixin-plugin" }
