[versions]
# Core Versions
minecraft = "1.21.5"
java = "21"
neoform = "1.21.5-20250325.162830"

# Parchment
parchment-minecraft = "1.21.5"
parchment = "2025.04.19"

# Fabric
fabric-loader = "0.16.13"
fabric-api = "0.121.0+1.21.5"
modmenu = "14.0.1"

# NeoForge
neoforge = "21.5.50-beta"

# Forge
forge = "55.1.0"

# Libraries
mixin = "0.8.5"
mixinextras = "0.4.1"
gson = "2.10.1"
forge-config-api-port = "21.5.3"

# Amber
amber = "4.2.2+1.21.5"

# Gradle Plugins
fabric-loom-plugin = "1.10-SNAPSHOT"
neoforge-moddev-plugin = "2.0.140"
modpublisher-plugin = "2.1.6"
forgegradle-plugin = "[6.0.47,6.2)"
mixin-plugin = "0.7-SNAPSHOT"

[libraries]
# Core Dependencies
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Mixin
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixin-extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

# Forge
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

# Parchment
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.5", version.ref = "parchment" }

# Forge Config API Port
forgeconfigapiport-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "forge-config-api-port" }
forgeconfigapiport-neoforge = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-neoforge", version.ref = "forge-config-api-port" }
forgeconfigapiport-common-neoforgeapi = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forge-config-api-port" }
forgeconfigapiport-forge = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-forge", version.ref = "forge-config-api-port" }

# Amber (all platforms)
amber = { group = "com.iamkaf.amber", name = "amber-common", version.ref = "amber" }
amber-fabric = { group = "com.iamkaf.amber", name = "amber-fabric", version.ref = "amber" }
amber-neoforge = { group = "com.iamkaf.amber", name = "amber-neoforge", version.ref = "amber" }
amber-forge = { group = "com.iamkaf.amber", name = "amber-forge", version.ref = "amber" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom-plugin" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev-plugin" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher-plugin" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle-plugin" }
mixin = { id = "org.spongepowered.mixin", version.ref = "mixin-plugin" }
